/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORT_H_RPCGEN
#define _AIRPORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

typedef float latitude;

typedef float longitude;

typedef char *placeName;

typedef struct airportNode *airportList;

struct searchedCity {
	char *city;
	char state[2];
	latitude lat;
	longitude lon;
};
typedef struct searchedCity searchedCity;

struct airportNode {
	char code[3];
	placeName name;
	char state[2];
	float distance;
	airportList next;
};
typedef struct airportNode airportNode;

struct output {
	searchedCity cityData;
	airportList list;
};
typedef struct output output;

struct placeair_ret {
	int err;
	union {
		output list;
	} placeair_ret_u;
};
typedef struct placeair_ret placeair_ret;

#define SEND_COORD_PROG 0x33337778
#define SEND_COORD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COORD 1
extern  airportList * coord_1(searchedCity *, CLIENT *);
extern  airportList * coord_1_svc(searchedCity *, struct svc_req *);
extern int send_coord_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COORD 1
extern  airportList * coord_1();
extern  airportList * coord_1_svc();
extern int send_coord_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_latitude (XDR *, latitude*);
extern  bool_t xdr_longitude (XDR *, longitude*);
extern  bool_t xdr_placeName (XDR *, placeName*);
extern  bool_t xdr_airportList (XDR *, airportList*);
extern  bool_t xdr_searchedCity (XDR *, searchedCity*);
extern  bool_t xdr_airportNode (XDR *, airportNode*);
extern  bool_t xdr_output (XDR *, output*);
extern  bool_t xdr_placeair_ret (XDR *, placeair_ret*);

#else /* K&R C */
extern bool_t xdr_latitude ();
extern bool_t xdr_longitude ();
extern bool_t xdr_placeName ();
extern bool_t xdr_airportList ();
extern bool_t xdr_searchedCity ();
extern bool_t xdr_airportNode ();
extern bool_t xdr_output ();
extern bool_t xdr_placeair_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORT_H_RPCGEN */
