
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = place_client
PASERVER = pa_server
ASERVER = airport_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_PA_SVC.c = 
SOURCES_PA_SVC.h = 
SOURCES_A_SVC.c = 
SOURCES_A_SVC.h = 
SOURCES.x = place.x airport.x

TARGETS_CLNT.c = place_clnt.c place_client.c place_xdr.c 
TARGETS_PA_SVC.c = place_svc.c place_server.c place_xdr.c airport_clnt.c
TARGETS_A_SVC.c = airport_svc.c airport_server.c place_xdr.c
TARGETS = place.h place_xdr.c airport_xdr.c place_clnt.c airport_clnt.c place_svc.c airport_svc.c place_client.c airport_client.c place_server.c airport_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_PA_SVC = $(SOURCES_PA_SVC.c:%.c=%.o) $(TARGETS_PA_SVC.c:%.c=%.o)
OBJECTS_A_SVC = $(SOURCES_A_SVC.c:%.c=%.o) $(TARGETS_A_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(PASERVER) $(ASERVER)

#$(TARGETS) : $(SOURCES.x) 
#	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_PA_SVC) : $(SOURCES_PA_SVC.c) $(SOURCES_PA_SVC.h) $(TARGETS_PA_SVC.c) 

$(OBJECTS_A_SVC) : $(SOURCES_A_SVC.c) $(SOURCES_A_SVC.h) $(TARGETS_A_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(PASERVER) : $(OBJECTS_PA_SVC) 
	$(LINK.c) -o $(PASERVER) $(OBJECTS_PA_SVC) $(LDLIBS)

$(ASERVER) : $(OBJECTS_A_SVC) 
	$(LINK.c) -o $(ASERVER) $(OBJECTS_A_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_PA_SVC) $(OBJECTS_A_SVC) $(CLIENT) $(PASERVER) $(ASERVER)

