/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"
#include <errno.h>

void
send_place_prog_1(char *host, char *city, char state[2])
{
	CLIENT *clnt;			// Client
	placeair_ret  *result_1;	// Return output or err
	placeName  place_1_arg;		// Name to search trie for place

#ifndef	DEBUG
	// Create client connection to place server
	clnt = clnt_create (host, SEND_PLACE_PROG, SEND_PLACE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	// TODO: adjust user input
	place_1_arg = "Seattle";	
	// Search trie of places for user request
	result_1 = place_1(&place_1_arg, clnt);

	// Check if result was returned correctly
	if (result_1 == (placeair_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG

	// Destroy client
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *city;
	char state[2];

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	// Get host from command line argument
	host = argv[1];

	// Get city from command line argument
	city = argv[2];

	// Get state from command line argument
	strcpy(state,argv[3]);

	
	send_place_prog_1 (host, city, state);
exit (0);
}
