/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"
#include <errno.h>

extern char* airportHost;

void
send_coord_prog_1(searchedCity *place)
{
	CLIENT *clnt;
	airportList  *result_1;
	searchedCity  coord_1_arg;

	coord_1_arg = *place;
	
	printf("1: %s, %s, %f, %f\n", coord_1_arg.city, coord_1_arg.state, coord_1_arg.lat, coord_1_arg.lon);
#ifndef	DEBUG
	clnt = clnt_create (airportHost, SEND_COORD_PROG, SEND_COORD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (airportHost);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = coord_1(&coord_1_arg, clnt);
	if (result_1 == (airportList *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("returned from airport server\n");
	//printf("%s, %s, %s, %f\n", *result_1->code ,result_1->name, result_1->state, result_1->distance);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


placeair_ret *
place_1_svc(placeName *argp, struct svc_req *rqstp)
{
	static placeair_ret  result;
	airportList node;
	airportList *nodePointer;
	searchedCity foundPlace;
	result.err = 0;
	printf("%s\n", *argp);
	nodePointer = &result.placeair_ret_u.list.list;
	node = *nodePointer = (airportNode*)malloc(sizeof(airportNode));

	if(node == (airportNode *) NULL) {
		result.err = errno;
		return(&result);
	}

	node->code = "124";
	node->name = "Phoenix";
	node->state = "AZ";
	node->distance = 66.0;
	nodePointer = &node->next;
	
	*nodePointer = (airportList)NULL;
		

	foundPlace.city = "Seattle";
	foundPlace.state = "WA";
	foundPlace.lat = 100.1;
	foundPlace.lon = 100.2;

	printf("1: %s, %s, %f, %f\n", foundPlace.city, foundPlace.state, foundPlace.lat, foundPlace.lon);
	result.placeair_ret_u.list.cityData.city = foundPlace.city;
	result.placeair_ret_u.list.cityData.state = foundPlace.state;
	result.placeair_ret_u.list.cityData.lat = foundPlace.lat;
	result.placeair_ret_u.list.cityData.lon = foundPlace.lon;
	result.placeair_ret_u.list.list->code = "123";	
	result.placeair_ret_u.list.list->name = "Seattle";
	result.placeair_ret_u.list.list->state = "WA";
	result.placeair_ret_u.list.list->distance = 123.1;
	//result.placeair_ret_u.list.list->next = "WA";
	// Airport server nearest neighbor search
	send_coord_prog_1(&foundPlace);

	return &result;
	/*
	 * insert server code here
	 */

}
