/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"
#include <errno.h>

extern char* airportHost;

void
send_coord_prog_1(searchedCity *place)
{
	CLIENT *clnt;
	airportList  *result_1;
	searchedCity  coord_1_arg;

	coord_1_arg.city = place->city;	
	strcpy(coord_1_arg.state, place->state);
	coord_1_arg.lat = place->lat;
	coord_1_arg.lon = place->lon;

	//Todo: Test if this works
	//coord_1_arg = place;

#ifndef	DEBUG
	clnt = clnt_create (airportHost, SEND_COORD_PROG, SEND_COORD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (airportHost);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = coord_1(&coord_1_arg, clnt);
	if (result_1 == (airportList *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

placeair_ret *
place_1_svc(placeName *argp, struct svc_req *rqstp)
{
	static placeair_ret  result;
	searchedCity coord_1_arg;
	result.err = 0;	
	
	coord_1_arg.city = "Seattle";	
	strcpy(coord_1_arg.state,"WA");
	coord_1_arg.lat = 70.7;
	coord_1_arg.lon = 56.5;
	
	
	/*
	 * insert server code here
	 */

	// Airport server nearest neighbor search
	send_coord_prog_1(&coord_1_arg);
	
	return &result;
}
