/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"
//#include "coord_client.h"


void
send_coord_prog_1(char *host)
{	
	printf("reached the send_coord_prog_1 \n");
	CLIENT *clnt;
	airportList  *result_1;
	searchedCity  coord_1_arg;
	//Test Code
	searchedCity thisCity;
	thisCity.city="city";
	thisCity.state="state";
	thisCity.lat=100;
	thisCity.lon=100;

	coord_1_arg = thisCity;
#ifndef	DEBUG
	clnt = clnt_create (host, SEND_COORD_PROG, SEND_COORD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	printf("Client Created \n");
#endif	/* DEBUG */

	result_1 = coord_1(&coord_1_arg, clnt);
	printf("sent things \n");
	if (result_1 == (airportList *) NULL) {
		printf("error on return \n");
		clnt_perror (clnt, "call failed");
		printf("after on return error\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

/* Removing for merge 
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	send_coord_prog_1 (host);
exit (0);
}
*/
