/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"

struct airportNode* createAirportNode() {

	struct airportNode* node = (struct airportNode*)malloc(sizeof(struct airportNode));
	strncpy(node->code, "456\0", 4);
	node->name = "newname";
	strncpy(node->state, "CA\0", 3);
	node->distance = 10.0;
	node->next = NULL;
	
	return node;
}
airportList *
coord_1_svc(searchedCity *argp, struct svc_req *rqstp)
{
	static airportList result;
	printf("got to the server function");

	searchedCity theCity = *argp;
	
	printf("The city lat is :%f \n", theCity.lat);
	//struct airportNode* node = (struct airportNode*)malloc(sizeof(struct airportNode));
	/*
	 * insert server code here
	 */
		
	printf("IN THE AIRPORT SERVER");
	strncpy(result->code, "123\0", 4);
	result->name = "seattle";
	strncpy(result->state, "WA\0", 3);
	result->distance = 5.0;
	result->next = createAirportNode();	

	printf("%s, %s, %f, %f\n", result->code, result->name, result->state, result->distance);
	/*
	 * insert server code here
	 */

	return &result;
}


