/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"
#include <errno.h>

void
send_place_prog_1(char *host, char *place)
{
	CLIENT *clnt;
	readdir_ret  *result_1;
	placeName  place_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SEND_PLACE_PROG, SEND_PLACE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	// Assign search place string to variable
	place_1_arg = place;
	printf("Place: %s\n", place_1_arg);

	// Search for place and 5 nearest airports
	result_1 = place_1(&place_1_arg, clnt);

	// Check if function call was successful
	if (result_1 == (readdir_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	// 
	if (result_1->err != 0) {
		errno = result_1->err;
		perror(place);
	}

	// Todo: Traverse linked list of airports and print info
	
	// If unable to successfully free allocated memory
	if(!clnt_freeres(clnt, (xdrproc_t)xdr_readdir_ret, (char*)&result_1)){
		printf("Unable to free allocated memory!\n");
	}
	
	printf("State: %s\n", result_1->readdir_ret_u.list.cityData.state);
#ifndef	DEBUG
	
	// Destroy client
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;			// Host name
	char *place;			// Search place

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	// Assign command line arguments to variables
	host = argv[1];
	place = argv[2];

	// Call the client side function
	send_place_prog_1 (host, place);
exit (0);
}
