/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"
#include <errno.h>

extern char* airportHost;

void
send_coord_prog_1(searchedCity *place)
{	
	printf("reached the send_coord_prog_1 \n");
	
	CLIENT *clnt;
	airportList *result_1;
	searchedCity coord_1_arg;

	//Test Code
	/*searchedCity thisCity;
	thisCity.city="city";
	thisCity.state="state";
	thisCity.lat=100;
	thisCity.lon=100;*/
	
	coord_1_arg.city = place->city;
	coord_1_arg.state = place->state;
	coord_1_arg.lat = place->lat;
	coord_1_arg.lon = place->lon;

	//coord_1_arg = thisCity;

#ifndef	DEBUG
	clnt = clnt_create (airportHost, SEND_COORD_PROG, SEND_COORD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (airportHost);
		exit (1);
	}
	printf("Client Created \n");
#endif	/* DEBUG */

	printf("test: %s, %s, %f, %f\n", coord_1_arg.state, coord_1_arg.city, coord_1_arg.lat, coord_1_arg.lon);
	result_1 = coord_1(&coord_1_arg, clnt);
	printf("sent things \n");
	if (result_1 == (airportList *) NULL) {
		printf("error on return \n");
		clnt_perror (clnt, "call failed");
		printf("after on return error\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

readdir_ret *
place_1_svc(placeName *argp, struct svc_req *rqstp)
{
	static readdir_ret  result;
	searchedCity  coord_1_arg;
	result.err = 0;
	coord_1_arg.city="city";
	coord_1_arg.state="WA";
	coord_1_arg.lat=100.0;
	coord_1_arg.lon=100.0;
	/*
	 * insert server code here
	 */
	send_coord_prog_1(&coord_1_arg);
	return &result;
}
