/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "place.h"

bool_t
xdr_latitude (XDR *xdrs, latitude *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_longitude (XDR *xdrs, longitude *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placeName (XDR *xdrs, placeName *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportList (XDR *xdrs, airportList *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct airportNode), (xdrproc_t) xdr_airportNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_searchedCity (XDR *xdrs, searchedCity *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->city, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->state, 2))
		 return FALSE;
	 if (!xdr_latitude (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_longitude (xdrs, &objp->lon))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportNode (XDR *xdrs, airportNode *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->code, 3))
		 return FALSE;
	 if (!xdr_placeName (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->state, 2))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_airportList (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output (XDR *xdrs, output *objp)
{
	register int32_t *buf;

	 if (!xdr_searchedCity (xdrs, &objp->cityData))
		 return FALSE;
	 if (!xdr_airportList (xdrs, &objp->list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placeair_ret (XDR *xdrs, placeair_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_output (xdrs, &objp->placeair_ret_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
