/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"

char* pString(char* city, char* state) {
	
	static char userSearch[50];
	int j = 0;
	int count = 0;
	int n;
	
	// Concatenate state and city
	strcpy(userSearch, state);
	strcat(userSearch, city);
	
	// Make all characters lowercase
	while(userSearch[j]) {
		userSearch[j] = tolower(userSearch[j]);
		j++;
	}

	// Get rid of all spaces
	for(n = 0; n < strlen(userSearch); ++n) {
		if (userSearch[n] != ' ')
			userSearch[count++] = userSearch[n];
	}

	userSearch[count] = '\0';
	//printf("Searched for: %s\n", userSearch);
	return &userSearch[0];
}

void
send_place_prog_1(char *host, char *city, char *state)
{
	CLIENT *clnt;
	placeair_ret  *result_1;
	placeName  place_arg;
	char *str;
	// Prep the string to send to server
	str = pString(city, state);

#ifndef	DEBUG
	clnt = clnt_create (host, SEND_PLACE_PROG, SEND_PLACE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("%s\n", str);

	place_arg = &str[0];
	printf("place_arg: %s\n", place_arg);
	// Query the place server for the 5 nearest airports
	result_1 = place_1(&place_arg, clnt);

	// Check if function return was successful
	if (result_1 == (placeair_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	// Print the results
	printf("%s\n", result_1->placeair_ret_u.list.list->code);
#ifndef	DEBUG
	
	// Destory the client
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *city;
	char *state;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	city = argv[2];
	state = argv[3];
	send_place_prog_1 (host, city, state);
exit (0);
}

